CREATE TABLE IF NOT EXISTS `funnels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`strategyId` int,
	`name` varchar(255) NOT NULL,
	`goal` text,
	`stage` enum('awareness','consideration','conversion','retention') NOT NULL DEFAULT 'awareness',
	`channels` json,
	`steps` json,
	`kpis` json,
	`budgetPct` float,
	`entryPoint` text,
	`conversionEvent` text,
	`retargetingPath` text,
	`automationPath` text,
	`status` enum('draft','approved') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `funnels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `content_calendar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`funnelId` int,
	`platform` varchar(100) NOT NULL,
	`funnelStage` varchar(100),
	`objective` text,
	`concept` text,
	`brief` text,
	`caption` text,
	`ctaText` varchar(255),
	`visualNotes` text,
	`requiredAssets` json,
	`scheduledDate` timestamp,
	`week` int,
	`month` int,
	`copyStatus` enum('planned','briefed','copywritten','approved','published') NOT NULL DEFAULT 'planned',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_calendar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `campaign_builds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`funnelId` int,
	`name` varchar(255) NOT NULL,
	`platform` varchar(100) NOT NULL,
	`objective` varchar(255),
	`structure` json,
	`audiences` json,
	`budgetLogic` json,
	`abTestMatrix` json,
	`launchChecklist` json,
	`buildDocs` text,
	`status` enum('draft','ready','launched') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaign_builds_id` PRIMARY KEY(`id`)
);
